-- LearnFlux PostgreSQL baseline generated from the four legacy SQLite stores.
-- Do not edit after release; add a new numbered migration instead.

CREATE TABLE video_cache (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    platform TEXT NOT NULL,
                    url TEXT NOT NULL,
                    title TEXT,
                    author TEXT,
                    description TEXT,
                    media_id TEXT NOT NULL,
                    use_speaker_recognition INTEGER NOT NULL DEFAULT 0,
                    files_loc TEXT NOT NULL,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    UNIQUE(platform, media_id, use_speaker_recognition)
                );
CREATE TABLE task_status (
                    task_id TEXT PRIMARY KEY,
                    view_token TEXT NOT NULL,
                    url TEXT NOT NULL,
                    download_url TEXT,
                    platform TEXT,
                    media_id TEXT,
                    use_speaker_recognition INTEGER DEFAULT 0,
                    status TEXT NOT NULL DEFAULT 'queued',
                    title TEXT,
                    author TEXT,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    completed_at TIMESTAMP,
                    cache_id BIGINT,
                    llm_config TEXT,
                    error_message TEXT, progress_json TEXT, progress_reminders_json TEXT, source_file_path TEXT, last_heartbeat_at TIMESTAMP, owner_user_id TEXT,
                    FOREIGN KEY (cache_id) REFERENCES video_cache(id)
                );
CREATE INDEX idx_platform_media_id ON video_cache(platform, media_id);
CREATE INDEX idx_url ON video_cache(url);
CREATE INDEX idx_view_token ON task_status(view_token);
CREATE INDEX idx_task_status ON task_status(status);
CREATE INDEX idx_task_platform_media ON task_status(platform, media_id);
CREATE TABLE learning_collections (
                    id TEXT PRIMARY KEY,
                    title TEXT NOT NULL,
                    collection_type TEXT NOT NULL,
                    goal TEXT,
                    status TEXT NOT NULL DEFAULT 'draft',
                    summary_status TEXT NOT NULL DEFAULT 'not_started',
                    summary_markdown TEXT,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                , creator_name TEXT NOT NULL DEFAULT '', description TEXT NOT NULL DEFAULT '', import_method TEXT NOT NULL DEFAULT '', tags TEXT NOT NULL DEFAULT '', exported_at TIMESTAMP, owner_user_id TEXT, transcription_strategy TEXT NOT NULL DEFAULT 'local', transcription_concurrency INTEGER NOT NULL DEFAULT 1, transcription_revision INTEGER NOT NULL DEFAULT 0);
CREATE TABLE learning_collection_sources (
                    id TEXT PRIMARY KEY,
                    collection_id TEXT NOT NULL,
                    task_id TEXT NOT NULL,
                    view_token TEXT NOT NULL,
                    title TEXT NOT NULL,
                    source_type TEXT NOT NULL,
                    position INTEGER NOT NULL,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, content_sha256 TEXT,
                    FOREIGN KEY (collection_id) REFERENCES learning_collections(id)
                );
CREATE INDEX idx_learning_sources_collection
                ON learning_collection_sources(collection_id, position)
                ;
CREATE TABLE learning_collection_knowledge_maps (
                    id TEXT PRIMARY KEY,
                    collection_id TEXT NOT NULL,
                    scope TEXT NOT NULL,
                    source_id TEXT NOT NULL DEFAULT '',
                    status TEXT NOT NULL DEFAULT 'success',
                    map_json TEXT NOT NULL,
                    model TEXT NOT NULL DEFAULT '',
                    error_message TEXT NOT NULL DEFAULT '',
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    FOREIGN KEY (collection_id) REFERENCES learning_collections(id),
                    UNIQUE(collection_id, scope, source_id)
                );
CREATE INDEX idx_learning_maps_collection
                ON learning_collection_knowledge_maps(collection_id, scope, source_id)
                ;
CREATE TABLE study_notes (
                    id TEXT PRIMARY KEY,
                    view_token TEXT NOT NULL,
                    time_seconds DOUBLE PRECISION,
                    body TEXT NOT NULL,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                , owner_user_id TEXT, collection_id TEXT, source_id TEXT);
CREATE INDEX idx_study_notes_view_token
                ON study_notes(view_token, created_at)
                ;
CREATE TABLE journal_entries (
                    id TEXT PRIMARY KEY,
                    user_id TEXT NOT NULL,
                    entry_date TEXT NOT NULL,
                    entry_type TEXT NOT NULL,
                    title TEXT NOT NULL DEFAULT '',
                    body TEXT NOT NULL DEFAULT '',
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    UNIQUE(user_id, entry_date, entry_type)
                );
CREATE INDEX idx_journal_entries_user_date
                ON journal_entries(user_id, entry_date DESC, updated_at DESC)
                ;
CREATE TABLE journal_reviews (
                    id TEXT PRIMARY KEY,
                    user_id TEXT NOT NULL,
                    range_start TEXT NOT NULL,
                    range_end TEXT NOT NULL,
                    question TEXT NOT NULL,
                    answer TEXT NOT NULL,
                    model TEXT NOT NULL,
                    reasoning_effort TEXT,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                );
CREATE INDEX idx_journal_reviews_user_created
                ON journal_reviews(user_id, created_at DESC)
                ;
CREATE TABLE visual_documents (
                    id TEXT PRIMARY KEY,
                    owner_type TEXT NOT NULL,
                    owner_id TEXT NOT NULL,
                    document_type TEXT NOT NULL,
                    status TEXT NOT NULL,
                    request_key TEXT NOT NULL UNIQUE,
                    source_hash TEXT NOT NULL,
                    style TEXT NOT NULL,
                    document_json TEXT,
                    model TEXT,
                    error_message TEXT,
                    generation_token TEXT NOT NULL DEFAULT '',
                    created_at TEXT NOT NULL,
                    updated_at TEXT NOT NULL
                , progress_json TEXT);
CREATE INDEX idx_visual_documents_owner
                ON visual_documents(owner_type, owner_id, document_type, updated_at)
                ;
CREATE INDEX idx_visual_documents_status
                ON visual_documents(status, updated_at)
                ;
CREATE INDEX idx_task_heartbeat ON task_status(status, last_heartbeat_at);
CREATE TABLE content_marks (
                    id TEXT PRIMARY KEY,
                    user_key TEXT NOT NULL,
                    owner_type TEXT NOT NULL,
                    owner_id TEXT NOT NULL,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    UNIQUE(user_key, owner_type, owner_id)
                );
CREATE INDEX idx_content_marks_owner
                ON content_marks(owner_type, owner_id)
                ;
CREATE INDEX idx_content_marks_user_updated
                ON content_marks(user_key, updated_at DESC)
                ;
CREATE INDEX idx_study_notes_context
                ON study_notes(view_token, owner_user_id, collection_id, source_id, created_at)
                ;
CREATE TABLE study_note_documents (
                    id TEXT PRIMARY KEY,
                    owner_user_id TEXT NOT NULL,
                    context_key TEXT NOT NULL,
                    current_view_token TEXT NOT NULL,
                    collection_id TEXT NOT NULL DEFAULT '',
                    source_id TEXT NOT NULL DEFAULT '',
                    body TEXT NOT NULL DEFAULT '',
                    revision INTEGER NOT NULL DEFAULT 1,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    UNIQUE(owner_user_id, context_key)
                );
CREATE TABLE obsidian_bindings (
                    id TEXT PRIMARY KEY,
                    owner_user_id TEXT NOT NULL,
                    scope_type TEXT NOT NULL,
                    scope_id TEXT NOT NULL,
                    vault_id TEXT NOT NULL,
                    transcript_directory TEXT NOT NULL,
                    note_directory TEXT NOT NULL,
                    revision INTEGER NOT NULL DEFAULT 1,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    UNIQUE(owner_user_id, scope_type, scope_id, vault_id)
                );
CREATE TABLE obsidian_source_sync (
                    id TEXT PRIMARY KEY,
                    owner_user_id TEXT NOT NULL,
                    context_key TEXT NOT NULL,
                    current_view_token TEXT NOT NULL,
                    collection_id TEXT NOT NULL DEFAULT '',
                    source_id TEXT NOT NULL DEFAULT '',
                    transcript_relative_path TEXT,
                    transcript_synced_hash TEXT,
                    note_relative_path TEXT,
                    note_body_synced_hash TEXT,
                    note_managed_hash TEXT,
                    synced_at TIMESTAMP,
                    UNIQUE(owner_user_id, context_key)
                );
CREATE TABLE reading_documents (
                id TEXT PRIMARY KEY, owner_user_id TEXT NOT NULL, title TEXT NOT NULL,
                author TEXT, format TEXT NOT NULL, source_path TEXT NOT NULL,
                file_sha256 TEXT NOT NULL, file_size BIGINT NOT NULL, status TEXT NOT NULL,
                parse_error TEXT, cover_path TEXT, outline_json TEXT, parse_generation INTEGER NOT NULL DEFAULT 0,
                created_at TEXT NOT NULL, updated_at TEXT NOT NULL, last_opened_at TEXT, active_parse_run_id TEXT, parse_quality TEXT NOT NULL DEFAULT 'good', parse_warning_count INTEGER NOT NULL DEFAULT 0,
                UNIQUE(owner_user_id, file_sha256)
            );
CREATE TABLE reading_chapters (
                id TEXT PRIMARY KEY, document_id TEXT NOT NULL, position INTEGER NOT NULL,
                parent_id TEXT, title TEXT NOT NULL, source_locator_json TEXT NOT NULL,
                plain_text TEXT NOT NULL, sanitized_html TEXT NOT NULL, created_at TEXT NOT NULL, parse_run_id TEXT,
                FOREIGN KEY(document_id) REFERENCES reading_documents(id) ON DELETE CASCADE,
                FOREIGN KEY(parent_id) REFERENCES reading_chapters(id) ON DELETE SET NULL
            );
CREATE INDEX idx_reading_chapters_document_position
                ON reading_chapters(document_id, position);
CREATE TABLE reading_progress (
                owner_user_id TEXT NOT NULL, document_id TEXT NOT NULL, mode TEXT NOT NULL,
                locator_json TEXT NOT NULL, percent DOUBLE PRECISION NOT NULL, updated_at TEXT NOT NULL,
                PRIMARY KEY(owner_user_id, document_id),
                FOREIGN KEY(document_id) REFERENCES reading_documents(id) ON DELETE CASCADE
            );
CREATE TABLE reading_preferences (
                owner_user_id TEXT PRIMARY KEY, theme TEXT NOT NULL, font_family TEXT NOT NULL,
                font_size INTEGER NOT NULL, layout TEXT NOT NULL, sound_track TEXT NOT NULL,
                sound_volume DOUBLE PRECISION NOT NULL, updated_at TEXT NOT NULL
            );
CREATE TABLE reading_annotations (
                id TEXT PRIMARY KEY, owner_user_id TEXT NOT NULL, document_id TEXT NOT NULL,
                kind TEXT NOT NULL, locator_json TEXT NOT NULL, quote TEXT NOT NULL,
                note_body TEXT, color TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL,
                FOREIGN KEY(document_id) REFERENCES reading_documents(id) ON DELETE CASCADE
            );
CREATE INDEX idx_reading_annotations_owner_document_updated
                ON reading_annotations(owner_user_id, document_id, updated_at DESC);
CREATE TABLE focus_materials (
                id TEXT PRIMARY KEY, owner_user_id TEXT NOT NULL, source_type TEXT NOT NULL,
                source_id TEXT, source_title TEXT NOT NULL, quote TEXT NOT NULL, note TEXT,
                locator_json TEXT, consumed_at TEXT, created_at TEXT NOT NULL
            );
CREATE INDEX idx_focus_materials_owner_consumed_created
                ON focus_materials(owner_user_id, consumed_at, created_at DESC);
CREATE TABLE usage_events (
                    id TEXT PRIMARY KEY,
                    attempt_no INTEGER NOT NULL,
                    idempotency_key TEXT NOT NULL UNIQUE,
                    task_id TEXT NOT NULL,
                    step TEXT NOT NULL DEFAULT 'asr',
                    provider TEXT NOT NULL DEFAULT 'aliyun',
                    model TEXT NOT NULL,
                    estimated_quantity TEXT NOT NULL,
                    reported_quantity TEXT,
                    unit TEXT NOT NULL DEFAULT 'audio_second',
                    currency TEXT NOT NULL DEFAULT 'CNY',
                    unit_price TEXT NOT NULL,
                    estimated_cost TEXT NOT NULL,
                    calculated_cost TEXT,
                    billed_cost TEXT,
                    remote_status TEXT NOT NULL,
                    materialization_status TEXT NOT NULL,
                    elapsed_seconds TEXT,
                    error_code TEXT,
                    owner_key TEXT NOT NULL,
                    provider_task_id TEXT,
                    sample_sha256 TEXT NOT NULL,
                    platform TEXT NOT NULL,
                    media_id TEXT NOT NULL,
                    output_name TEXT NOT NULL,
                    lease_owner TEXT,
                    lease_expires_at TEXT,
                    lease_heartbeat_at TEXT,
                    continuation_json TEXT,
                    postprocess_key TEXT,
                    postprocess_status TEXT,
                    created_at TEXT NOT NULL,
                    updated_at TEXT NOT NULL
                , provider_error_code TEXT, provider_request_id TEXT);
CREATE UNIQUE INDEX ux_usage_events_task_attempt
                ON usage_events(task_id, step, attempt_no)
                ;
CREATE TABLE cloud_quotes (
                    task_id TEXT PRIMARY KEY,
                    media_ref TEXT NOT NULL,
                    media_sha256 TEXT NOT NULL,
                    duration_seconds TEXT NOT NULL,
                    billable_seconds INTEGER NOT NULL,
                    model TEXT NOT NULL,
                    unit_price TEXT NOT NULL,
                    max_cost TEXT NOT NULL,
                    status TEXT NOT NULL,
                    token_hash TEXT,
                    lease_owner TEXT,
                    lease_expires_at TEXT,
                    attempt_no INTEGER,
                    expires_at TEXT NOT NULL,
                    created_at TEXT NOT NULL,
                    updated_at TEXT NOT NULL
                    ,continuation_json TEXT
                );
CREATE TABLE reading_deletion_jobs (
                id TEXT PRIMARY KEY, source_path TEXT NOT NULL,
                asset_dir TEXT NOT NULL, created_at TEXT NOT NULL
            );
CREATE TABLE transcription_jobs (
                    task_id TEXT PRIMARY KEY,
                    owner_user_id TEXT NOT NULL,
                    source_kind TEXT NOT NULL,
                    source_ref TEXT NOT NULL,
                    strategy TEXT NOT NULL,
                    payload_json TEXT NOT NULL,
                    status TEXT NOT NULL,
                    lease_owner TEXT,
                    lease_expires_at TEXT,
                    attempt_count INTEGER NOT NULL DEFAULT 0,
                    created_at TEXT NOT NULL,
                    updated_at TEXT NOT NULL
                );
CREATE TABLE upload_sessions (
                    id TEXT PRIMARY KEY,
                    owner_user_id TEXT NOT NULL,
                    object_key TEXT NOT NULL UNIQUE,
                    status TEXT NOT NULL,
                    max_bytes BIGINT NOT NULL,
                    actual_bytes BIGINT,
                    expires_at TEXT NOT NULL,
                    task_id TEXT,
                    created_at TEXT NOT NULL,
                    updated_at TEXT NOT NULL
                );
CREATE UNIQUE INDEX uq_learning_sources_collection_content_sha256
                ON learning_collection_sources(collection_id, content_sha256)
                WHERE content_sha256 IS NOT NULL
                ;
CREATE TABLE reading_parse_runs (
                id TEXT PRIMARY KEY, document_id TEXT NOT NULL, generation INTEGER NOT NULL,
                parent_run_id TEXT, parser_version TEXT NOT NULL, status TEXT NOT NULL,
                created_at TEXT NOT NULL, updated_at TEXT NOT NULL,
                UNIQUE(document_id, generation),
                FOREIGN KEY(document_id) REFERENCES reading_documents(id) ON DELETE CASCADE,
                FOREIGN KEY(parent_run_id) REFERENCES reading_parse_runs(id) ON DELETE SET NULL
            );
CREATE INDEX idx_reading_parse_runs_document_generation
                ON reading_parse_runs(document_id, generation DESC);
CREATE TABLE reading_page_analyses (
                id TEXT PRIMARY KEY, creating_run_id TEXT NOT NULL,
                source_page INTEGER NOT NULL, retry_profile TEXT NOT NULL,
                extraction_mode TEXT NOT NULL, quality_status TEXT NOT NULL,
                quality_score DOUBLE PRECISION NOT NULL, issue_codes_json TEXT NOT NULL,
                created_at TEXT NOT NULL,
                FOREIGN KEY(creating_run_id) REFERENCES reading_parse_runs(id) ON DELETE CASCADE
            );
CREATE INDEX idx_reading_page_analyses_run_page
                ON reading_page_analyses(creating_run_id, source_page);
CREATE TABLE reading_run_pages (
                run_id TEXT NOT NULL, source_page INTEGER NOT NULL,
                analysis_id TEXT NOT NULL,
                PRIMARY KEY(run_id, source_page),
                FOREIGN KEY(run_id) REFERENCES reading_parse_runs(id) ON DELETE CASCADE,
                FOREIGN KEY(analysis_id) REFERENCES reading_page_analyses(id) ON DELETE RESTRICT
            );
CREATE TABLE reading_page_blocks (
                analysis_id TEXT NOT NULL, block_index INTEGER NOT NULL,
                text TEXT NOT NULL, bbox_json TEXT, confidence DOUBLE PRECISION,
                kind TEXT NOT NULL, reading_order INTEGER NOT NULL,
                PRIMARY KEY(analysis_id, block_index),
                FOREIGN KEY(analysis_id) REFERENCES reading_page_analyses(id) ON DELETE CASCADE
            );
CREATE INDEX idx_reading_page_blocks_analysis_order
                ON reading_page_blocks(analysis_id, reading_order);
CREATE TABLE reading_locator_resolutions (
                id TEXT PRIMARY KEY, owner_user_id TEXT NOT NULL,
                document_id TEXT NOT NULL, target_run_id TEXT NOT NULL,
                target_type TEXT NOT NULL, old_locator_json TEXT NOT NULL,
                resolved_locator_json TEXT, status TEXT NOT NULL,
                reason TEXT NOT NULL, created_at TEXT NOT NULL,
                FOREIGN KEY(document_id) REFERENCES reading_documents(id) ON DELETE CASCADE,
                FOREIGN KEY(target_run_id) REFERENCES reading_parse_runs(id) ON DELETE CASCADE
            );
CREATE INDEX idx_reading_locator_resolutions_document_run
                ON reading_locator_resolutions(document_id, target_run_id, created_at);
CREATE TABLE reading_schema_migrations (
                version INTEGER PRIMARY KEY, applied_at TEXT NOT NULL
            );
CREATE INDEX idx_reading_chapters_document_run_position
               ON reading_chapters(document_id, parse_run_id, position);
CREATE UNIQUE INDEX uq_learning_collections_owner_creator_title
                ON learning_collections(
                    COALESCE(owner_user_id, ''),
                    creator_name,
                    title
                )
                ;
CREATE TABLE obsidian_knowledge_bindings (
                    id TEXT PRIMARY KEY, owner_user_id TEXT NOT NULL, scope_type TEXT NOT NULL,
                    scope_id TEXT NOT NULL, vault_id TEXT NOT NULL, category TEXT NOT NULL,
                    collection_directory TEXT NOT NULL DEFAULT '', revision INTEGER NOT NULL DEFAULT 1,
                    created_at TIMESTAMP, updated_at TIMESTAMP,
                    UNIQUE(owner_user_id, scope_type, scope_id, vault_id)
                );
CREATE TABLE obsidian_knowledge_sync (
                    id TEXT PRIMARY KEY, owner_user_id TEXT NOT NULL, context_key TEXT NOT NULL,
                    current_view_token TEXT NOT NULL, collection_id TEXT NOT NULL DEFAULT '',
                    source_id TEXT NOT NULL DEFAULT '', raw_relative_path TEXT, raw_synced_hash TEXT,
                    analysis_relative_path TEXT, analysis_synced_hash TEXT, synced_at TIMESTAMP,
                    UNIQUE(owner_user_id, context_key)
                );
CREATE TABLE learning_collection_summary_jobs (
                    job_id TEXT PRIMARY KEY,
                    collection_id TEXT NOT NULL UNIQUE,
                    status TEXT NOT NULL DEFAULT 'queued',
                    phase TEXT NOT NULL DEFAULT 'queued',
                    worker_id TEXT NOT NULL DEFAULT '',
                    attempt INTEGER NOT NULL DEFAULT 0,
                    total_modules INTEGER NOT NULL DEFAULT 0,
                    completed_modules INTEGER NOT NULL DEFAULT 0,
                    progress_message TEXT NOT NULL DEFAULT '',
                    error_message TEXT NOT NULL DEFAULT '',
                    started_at TIMESTAMP,
                    heartbeat_at TIMESTAMP,
                    lease_until TIMESTAMP,
                    deadline_seconds INTEGER NOT NULL DEFAULT 720,
                    deadline_at TIMESTAMP,
                    completed_at TIMESTAMP,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    FOREIGN KEY (collection_id) REFERENCES learning_collections(id)
                );
CREATE INDEX idx_learning_summary_jobs_status
                ON learning_collection_summary_jobs(status, created_at)
                ;
CREATE TABLE learning_collection_summary_modules (
                    job_id TEXT NOT NULL,
                    module_index INTEGER NOT NULL,
                    title TEXT NOT NULL DEFAULT '',
                    role TEXT NOT NULL DEFAULT '',
                    rationale TEXT NOT NULL DEFAULT '',
                    source_numbers TEXT NOT NULL DEFAULT '[]',
                    status TEXT NOT NULL DEFAULT 'queued',
                    markdown TEXT NOT NULL DEFAULT '',
                    error_message TEXT NOT NULL DEFAULT '',
                    started_at TIMESTAMP,
                    completed_at TIMESTAMP,
                    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    PRIMARY KEY (job_id, module_index),
                    FOREIGN KEY (job_id) REFERENCES learning_collection_summary_jobs(job_id)
                );
CREATE TABLE schema_version (
                        version INTEGER NOT NULL
                    );
CREATE TABLE api_audit_logs (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                api_key_masked TEXT NOT NULL,
                user_id TEXT,
                endpoint TEXT NOT NULL,
                video_url TEXT,
                request_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                processing_time_ms INTEGER,
                status_code INTEGER,
                task_id TEXT,
                user_agent TEXT,
                remote_ip TEXT
            , wechat_webhook TEXT);
CREATE INDEX idx_api_key ON api_audit_logs(api_key_masked);
CREATE INDEX idx_user_id ON api_audit_logs(user_id);
CREATE INDEX idx_request_time ON api_audit_logs(request_time);
CREATE INDEX idx_endpoint ON api_audit_logs(endpoint);
CREATE INDEX idx_wechat_webhook ON api_audit_logs(wechat_webhook);
CREATE TABLE blogger (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    platform TEXT NOT NULL,
                    platform_user_id TEXT NOT NULL,
                    handle TEXT NOT NULL,
                    avatar_url TEXT,
                    bio TEXT,
                    follower_count INTEGER NOT NULL DEFAULT 0,
                    media_types TEXT NOT NULL DEFAULT '[]',
                    is_subscribed INTEGER NOT NULL DEFAULT 0,
                    pinned INTEGER NOT NULL DEFAULT 0,
                    last_post_at TIMESTAMP,
                    subscribed_at TIMESTAMP,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    UNIQUE(platform, platform_user_id)
                );
CREATE TABLE content (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    blogger_id BIGINT NOT NULL,
                    platform TEXT NOT NULL,
                    platform_item_id TEXT NOT NULL,
                    media_type TEXT NOT NULL,
                    title TEXT NOT NULL,
                    original_url TEXT NOT NULL,
                    cover_url TEXT,
                    published_at TIMESTAMP,
                    like_count INTEGER NOT NULL DEFAULT 0,
                    collect_count INTEGER NOT NULL DEFAULT 0,
                    comment_count INTEGER NOT NULL DEFAULT 0,
                    share_count INTEGER NOT NULL DEFAULT 0,
                    stats_synced_at TIMESTAMP,
                    source TEXT NOT NULL DEFAULT 'feed',
                    analysis_status TEXT NOT NULL DEFAULT 'pending',
                    latest_analysis_id BIGINT,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    UNIQUE(platform, platform_item_id),
                    FOREIGN KEY (blogger_id) REFERENCES blogger(id)
                );
CREATE INDEX idx_content_blogger_pub ON content(blogger_id, published_at DESC);
CREATE INDEX idx_content_status ON content(analysis_status);
CREATE INDEX idx_content_pub ON content(published_at DESC);
CREATE INDEX idx_content_media ON content(media_type);
CREATE TABLE analysis (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    content_id BIGINT NOT NULL,
                    media_type TEXT NOT NULL,
                    status TEXT NOT NULL,
                    result_json TEXT NOT NULL DEFAULT '{}',
                    error_message TEXT,
                    prompt_version INTEGER,
                    model TEXT,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    FOREIGN KEY (content_id) REFERENCES content(id)
                );
CREATE INDEX idx_analysis_content ON analysis(content_id);
CREATE TABLE analysis_cost (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    analysis_id BIGINT NOT NULL,
                    content_id BIGINT NOT NULL,
                    blogger_id BIGINT,
                    in_tokens INTEGER NOT NULL DEFAULT 0,
                    out_tokens INTEGER NOT NULL DEFAULT 0,
                    total_cost DOUBLE PRECISION NOT NULL DEFAULT 0,
                    currency TEXT NOT NULL DEFAULT 'CNY',
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                );
CREATE INDEX idx_cost_blogger ON analysis_cost(blogger_id);
CREATE INDEX idx_cost_created ON analysis_cost(created_at);
CREATE TABLE prompt_template (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    media_type TEXT NOT NULL,
                    version INTEGER NOT NULL DEFAULT 1,
                    body TEXT NOT NULL,
                    is_active INTEGER NOT NULL DEFAULT 1,
                    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                );
CREATE INDEX idx_prompt_media ON prompt_template(media_type, is_active);
CREATE TABLE config_overrides (config_key TEXT PRIMARY KEY, config_value TEXT NOT NULL, updated_at TEXT);
