"""Database ports shared by the local SQLite and PostgreSQL runtimes.

The project historically used SQLite connections directly. The PostgreSQL
adapter exposes the small subset of Python's ``sqlite3`` API used by the
repositories so business code can be migrated incrementally while both
backends remain covered by the same contracts.
"""

from __future__ import annotations

import re
import sqlite3
from contextlib import contextmanager
from pathlib import Path
from typing import Any, Iterable, Iterator, Sequence

from psycopg_pool import ConnectionPool


class CompatRow(dict):
    """Mapping row that also supports SQLite-style integer indexing."""

    def __init__(self, names: Sequence[str], values: Sequence[Any]) -> None:
        super().__init__(zip(names, values))
        self._values = tuple(values)

    def __getitem__(self, key):
        if isinstance(key, int):
            return self._values[key]
        return super().__getitem__(key)


def _compat_row_factory(cursor):
    names = [column.name for column in (cursor.description or ())]

    def make_row(values):
        return CompatRow(names, values)

    return make_row


def _replace_qmark_placeholders(statement: str) -> str:
    """Replace qmark placeholders outside SQL string literals."""

    result: list[str] = []
    quote: str | None = None
    index = 0
    while index < len(statement):
        char = statement[index]
        if quote:
            result.append(char)
            if char == quote:
                if index + 1 < len(statement) and statement[index + 1] == quote:
                    result.append(statement[index + 1])
                    index += 1
                else:
                    quote = None
        elif char in ("'", '"'):
            quote = char
            result.append(char)
        elif char == "?":
            result.append("%s")
        else:
            result.append(char)
        index += 1
    return "".join(result)


def _escape_literal_percents(statement: str) -> str:
    """Escape percent signs inside SQL literals for psycopg parameters."""

    result: list[str] = []
    quote: str | None = None
    index = 0
    while index < len(statement):
        char = statement[index]
        if quote:
            if char == "%":
                result.append("%%")
            else:
                result.append(char)
            if char == quote:
                if index + 1 < len(statement) and statement[index + 1] == quote:
                    result.append(statement[index + 1])
                    index += 1
                else:
                    quote = None
        else:
            result.append(char)
            if char in ("'", '"'):
                quote = char
        index += 1
    return "".join(result)


def _split_sql_script(script: str) -> list[str]:
    """Split the simple DDL scripts used by repositories into statements."""

    script = "\n".join(
        line for line in script.splitlines() if not line.lstrip().startswith("--")
    )
    statements: list[str] = []
    current: list[str] = []
    quote: str | None = None
    index = 0
    while index < len(script):
        char = script[index]
        if quote:
            current.append(char)
            if char == quote:
                if index + 1 < len(script) and script[index + 1] == quote:
                    current.append(script[index + 1])
                    index += 1
                else:
                    quote = None
        elif char in ("'", '"'):
            quote = char
            current.append(char)
        elif char == ";":
            statement = "".join(current).strip()
            if statement:
                statements.append(statement)
            current = []
        else:
            current.append(char)
        index += 1
    statement = "".join(current).strip()
    if statement:
        statements.append(statement)
    return statements


def _translate_postgres_sql(statement: str) -> str:
    """Translate the small SQLite SQL dialect surface used by the project."""

    translated = statement.strip()
    if translated.upper() == "BEGIN IMMEDIATE":
        return "BEGIN"
    translated = re.sub(r"\bIFNULL\s*\(", "COALESCE(", translated, flags=re.I)
    translated = re.sub(
        r"\bINTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT\b",
        "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        translated,
        flags=re.I,
    )
    translated = re.sub(r"\bDATETIME\b", "TIMESTAMP", translated, flags=re.I)
    translated = re.sub(r"\bBOOLEAN\b", "INTEGER", translated, flags=re.I)
    translated = re.sub(r"\bREAL\b", "DOUBLE PRECISION", translated, flags=re.I)
    ignore_insert = re.match(r"(?is)^\s*INSERT\s+OR\s+IGNORE\s+INTO\b", translated)
    if ignore_insert:
        translated = re.sub(
            r"(?is)^\s*INSERT\s+OR\s+IGNORE\s+INTO\b",
            "INSERT INTO",
            translated,
            count=1,
        )
        translated = translated.rstrip().rstrip(";") + " ON CONFLICT DO NOTHING"
    return _replace_qmark_placeholders(translated)


class SQLiteControlDatabase:
    """Create short SQLite connections with explicit transactional writes."""

    dialect = "sqlite"

    def __init__(self, path: str | Path) -> None:
        self.path = str(path)
        if self.path != ":memory:":
            Path(self.path).parent.mkdir(parents=True, exist_ok=True)

    def connect(self) -> sqlite3.Connection:
        connection = sqlite3.connect(self.path, timeout=30, isolation_level=None)
        connection.row_factory = sqlite3.Row
        connection.execute("PRAGMA busy_timeout = 30000")
        connection.execute("PRAGMA foreign_keys = ON")
        return connection

    @contextmanager
    def transaction(self) -> Iterator[sqlite3.Connection]:
        connection = self.connect()
        try:
            connection.execute("BEGIN IMMEDIATE")
            yield connection
            connection.commit()
        except Exception:
            if connection.in_transaction:
                connection.rollback()
            raise
        finally:
            connection.close()

    def close(self) -> None:
        """SQLite connections are short-lived and need no pool shutdown."""


class _NoopCursor:
    rowcount = 0
    lastrowid = None

    def fetchone(self):
        return None

    def fetchall(self):
        return []

    def close(self) -> None:
        return None

    def __iter__(self):
        return iter(())

    def __enter__(self):
        return self

    def __exit__(self, *_args):
        self.close()


class _PostgresCursor:
    """Cursor wrapper implementing the sqlite3 methods used by repositories."""

    def __init__(self, connection: "_PostgresConnection", raw_cursor=None) -> None:
        self._connection = connection
        self._cursor = raw_cursor or connection._raw_connection.cursor()

    def execute(self, statement: str, parameters=None):
        special = self._connection._execute_pragma(statement)
        if special is not None:
            self.close()
            self._cursor = (
                special._cursor
                if isinstance(special, _PostgresCursor)
                else special
            )
            return self
        translated = _translate_postgres_sql(statement)
        if parameters is None:
            self._cursor.execute(translated)
        else:
            self._cursor.execute(_escape_literal_percents(translated), parameters)
        return self

    def executemany(self, statement: str, parameters: Iterable[Sequence[Any]]):
        self._cursor.executemany(
            _escape_literal_percents(_translate_postgres_sql(statement)), parameters
        )
        return self

    def executescript(self, script: str):
        for statement in _split_sql_script(script):
            self.execute(statement)
        return self

    def fetchone(self):
        return self._cursor.fetchone()

    def fetchall(self):
        return self._cursor.fetchall()

    @property
    def rowcount(self) -> int:
        return self._cursor.rowcount

    @property
    def lastrowid(self):
        row = self._connection._raw_connection.execute("SELECT LASTVAL()").fetchone()
        return row[0] if row else None

    @property
    def description(self):
        return self._cursor.description

    def close(self) -> None:
        self._cursor.close()

    def __iter__(self):
        return iter(self._cursor)

    def __enter__(self):
        return self

    def __exit__(self, *_args):
        self.close()


class _PostgresConnection:
    def __init__(self, raw_connection, release) -> None:
        self._raw_connection = raw_connection
        self._release = release
        self._closed = False

    def cursor(self) -> _PostgresCursor:
        return _PostgresCursor(self)

    def execute(self, statement: str, parameters=None):
        special = self._execute_pragma(statement)
        if special is not None:
            return special
        translated = _translate_postgres_sql(statement)
        raw_cursor = (
            self._raw_connection.execute(translated)
            if parameters is None
            else self._raw_connection.execute(
                _escape_literal_percents(translated), parameters
            )
        )
        return _PostgresCursor(self, raw_cursor)

    def executemany(self, statement: str, parameters: Iterable[Sequence[Any]]):
        return self.cursor().executemany(statement, parameters)

    def executescript(self, script: str):
        return self.cursor().executescript(script)

    def _execute_pragma(self, statement: str):
        normalized = statement.strip().rstrip(";")
        table_info = re.fullmatch(
            r"PRAGMA\s+table_info\s*\(\s*([^\)]+)\s*\)", normalized, re.I
        )
        if table_info:
            table_name = table_info.group(1).strip().strip('"`[]')
            raw = self._raw_connection.execute(
                """
                SELECT
                    (a.attnum - 1)::integer AS cid,
                    a.attname AS name,
                    pg_catalog.format_type(a.atttypid, a.atttypmod) AS type,
                    a.attnotnull::integer AS notnull,
                    pg_get_expr(d.adbin, d.adrelid) AS dflt_value,
                    COALESCE(i.indisprimary, FALSE)::integer AS pk
                FROM pg_catalog.pg_attribute a
                JOIN pg_catalog.pg_class c ON c.oid = a.attrelid
                JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
                LEFT JOIN pg_catalog.pg_attrdef d
                  ON d.adrelid = a.attrelid AND d.adnum = a.attnum
                LEFT JOIN pg_catalog.pg_index i
                  ON i.indrelid = a.attrelid AND i.indisprimary
                 AND a.attnum = ANY(i.indkey)
                WHERE n.nspname = current_schema()
                  AND c.relname = %s
                  AND a.attnum > 0
                  AND NOT a.attisdropped
                ORDER BY a.attnum
                """,
                (table_name,),
            )
            return _PostgresCursor(self, raw)
        index_list = re.fullmatch(
            r"PRAGMA\s+index_list\s*\(\s*([^\)]+)\s*\)", normalized, re.I
        )
        if index_list:
            table_name = index_list.group(1).strip().strip('"`[]')
            raw = self._raw_connection.execute(
                """
                SELECT
                    (ROW_NUMBER() OVER (ORDER BY ic.relname) - 1)::integer AS seq,
                    ic.relname AS name,
                    ix.indisunique::integer AS "unique",
                    'c'::text AS origin,
                    0::integer AS partial
                FROM pg_catalog.pg_index ix
                JOIN pg_catalog.pg_class tc ON tc.oid = ix.indrelid
                JOIN pg_catalog.pg_class ic ON ic.oid = ix.indexrelid
                JOIN pg_catalog.pg_namespace n ON n.oid = tc.relnamespace
                WHERE n.nspname = current_schema() AND tc.relname = %s
                ORDER BY ic.relname
                """,
                (table_name,),
            )
            return _PostgresCursor(self, raw)
        index_info = re.fullmatch(
            r"PRAGMA\s+index_info\s*\(\s*['\"]?([^\)'\"]+)['\"]?\s*\)",
            normalized,
            re.I,
        )
        if index_info:
            index_name = index_info.group(1).strip()
            raw = self._raw_connection.execute(
                """
                SELECT
                    (keys.ordinality - 1)::integer AS seqno,
                    a.attnum::integer AS cid,
                    a.attname AS name
                FROM pg_catalog.pg_class ic
                JOIN pg_catalog.pg_namespace n ON n.oid = ic.relnamespace
                JOIN pg_catalog.pg_index ix ON ix.indexrelid = ic.oid
                CROSS JOIN LATERAL unnest(ix.indkey)
                    WITH ORDINALITY AS keys(attnum, ordinality)
                JOIN pg_catalog.pg_attribute a
                  ON a.attrelid = ix.indrelid AND a.attnum = keys.attnum
                WHERE n.nspname = current_schema() AND ic.relname = %s
                ORDER BY keys.ordinality
                """,
                (index_name,),
            )
            return _PostgresCursor(self, raw)
        if normalized.upper().startswith("PRAGMA"):
            return _NoopCursor()
        return None

    @property
    def in_transaction(self) -> bool:
        return self._raw_connection.info.transaction_status.name != "IDLE"

    def commit(self) -> None:
        self._raw_connection.commit()

    def rollback(self) -> None:
        self._raw_connection.rollback()

    def close(self) -> None:
        if not self._closed:
            self._closed = True
            self._release(self._raw_connection)

    def __enter__(self):
        return self

    def __exit__(self, exc_type, _exc, _traceback):
        if exc_type is None:
            self.commit()
        else:
            self.rollback()
        return False


class PostgresControlDatabase:
    """Pooled PostgreSQL adapter matching the project's connection port."""

    dialect = "postgres"

    def __init__(self, dsn: str, *, max_size: int = 12) -> None:
        self.dsn = dsn
        self.pool = ConnectionPool(
            conninfo=dsn,
            min_size=0,
            max_size=max_size,
            kwargs={"autocommit": True, "row_factory": _compat_row_factory},
            open=True,
        )

    def connect(self) -> _PostgresConnection:
        raw = self.pool.getconn()
        return _PostgresConnection(raw, self.pool.putconn)

    @contextmanager
    def transaction(self) -> Iterator[_PostgresConnection]:
        connection = self.connect()
        try:
            with connection._raw_connection.transaction():
                yield connection
        finally:
            connection.close()

    def close(self) -> None:
        self.pool.close()
