#!/usr/bin/env python3
"""Synchronize the canonical LearnFlux navigation into production shells."""

from __future__ import annotations

import argparse
import hashlib
import html
import json
import re
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[1]
WEB_ROOT = PROJECT_ROOT / "src" / "web"
STATIC_ROOT = WEB_ROOT / "static"
TEMPLATE_ROOT = WEB_ROOT / "templates"
NAVIGATION_PATH = WEB_ROOT / "product-navigation.json"
FEATURE_CONFIG_PATH = STATIC_ROOT / "js" / "ui-features.js"

STATIC_TARGETS = {
    STATIC_ROOT / "index.html": "single_study",
    STATIC_ROOT / "collections.html": "collections",
    STATIC_ROOT / "study.html": "study_player",
    STATIC_ROOT / "visual-learning.html": "visual_learning",
    STATIC_ROOT / "focus-studio.html": "focus_studio",
    STATIC_ROOT / "reading.html": "reading",
    STATIC_ROOT / "review.html": "review",
    STATIC_ROOT / "trend-radar.html": "trend_radar",
    STATIC_ROOT / "history.html": "history",
    STATIC_ROOT / "settings.html": "settings",
}
DIRECT_STATIC = {
    STATIC_ROOT / "focus-studio.html",
    STATIC_ROOT / "history.html",
}
JINJA_TARGETS = (
    TEMPLATE_ROOT / "base.html",
    TEMPLATE_ROOT / "flywheel.html",
)
VIEWS_PATH = PROJECT_ROOT / "src" / "video_transcript_api" / "api" / "routes" / "views.py"
PARTIAL_PATH = TEMPLATE_ROOT / "partials" / "product_navigation.html"

NAV_RE = re.compile(
    r'(?P<indent>^[ \t]*)<nav class="sidebar-nav" aria-label="主导航">.*?^(?P=indent)</nav>',
    flags=re.MULTILINE | re.DOTALL,
)
MARKED_NAV_RE = re.compile(
    r'(?P<indent>^[ \t]*)<!-- PRODUCT_NAV_START:.*?^'
    r'(?P=indent)<!-- PRODUCT_NAV_END -->',
    flags=re.MULTILINE | re.DOTALL,
)
APP_SHELL_SCRIPT_RE = re.compile(
    r'^(?P<indent>[ \t]*)<script src="(?P<src>[^"]*app-shell\.js[^"]*)"(?P<rest>[^>]*)></script>',
    flags=re.MULTILINE,
)


def _load_navigation() -> dict:
    return json.loads(NAVIGATION_PATH.read_text(encoding="utf-8"))


def _feature_digest() -> str:
    return hashlib.sha256(FEATURE_CONFIG_PATH.read_bytes()).hexdigest()[:12]


def _static_asset_digest() -> str:
    digest = hashlib.sha256()
    for path in sorted((STATIC_ROOT / "css").rglob("*.css")):
        digest.update(path.relative_to(STATIC_ROOT).as_posix().encode())
        digest.update(path.read_bytes())
    for path in sorted((STATIC_ROOT / "js").rglob("*.js")):
        digest.update(path.relative_to(STATIC_ROOT).as_posix().encode())
        digest.update(path.read_bytes())
    return digest.hexdigest()[:12]


def _active_expression(item: dict) -> str:
    expressions: list[str] = []
    for match in item.get("matches", [item["href"]]):
        if match == "/":
            expressions.append("shell_path == '/'")
        else:
            expressions.append(f"shell_path.startswith('{match}')")
    return " or ".join(expressions)


def _exact_active_expression(item: dict) -> str:
    expressions: list[str] = []
    for match in item.get("matches", [item["href"]]):
        normalized = match.rstrip("/") or "/"
        expressions.append(f"shell_path == '{normalized}'")
        if normalized != "/":
            expressions.append(f"shell_path == '{normalized}/'")
    return " or ".join(expressions)


def _render_navigation(navigation: dict, *, active_id: str | None, jinja: bool) -> str:
    lines = [
        '<!-- PRODUCT_NAV_START: generated by scripts/sync_product_navigation.py -->',
        '<nav class="sidebar-nav" aria-label="主导航">',
    ]
    for group in navigation["groups"]:
        group_id = group["id"]
        group_classes = "nav-group nav-group-bottom" if group.get("bottom") else "nav-group"
        lines.extend([
            f'    <section class="{group_classes}" data-group="{group_id}" '
            f'aria-labelledby="nav-{group_id}-label">',
            f'        <button class="nav-group-toggle" id="nav-{group_id}-label" '
            f'type="button" data-group="{group_id}" aria-expanded="true" '
            f'aria-controls="nav-{group_id}-items">',
            f'            <span class="nav-group-label">{html.escape(group["label"])}</span>',
            '            <span class="nav-group-current" aria-hidden="true"></span>',
            '            <svg class="nav-group-chevron" viewBox="0 0 16 16" aria-hidden="true">'
            '<path d="m4 6 4 4 4-4"/></svg>',
            '        </button>',
            f'        <div class="nav-group-items" id="nav-{group_id}-items">',
        ])
        for item_id in group["items"]:
            item = navigation["items"][item_id]
            children = item.get("children", [])
            active_expression = _active_expression(item)
            if jinja:
                active = f" {{% if {active_expression} %}}is-active{{% endif %}}"
                current = "" if children else (
                    f" {{% if {active_expression} %}}aria-current=\"page\"{{% endif %}}"
                )
            else:
                active = " is-active" if item_id == active_id else ""
                current = ' aria-current="page"' if item_id == active_id and not children else ""
            aliases = ",".join(item.get("aliases", []))
            optional = ""
            if item.get("feature"):
                optional = f' data-feature="{item["feature"]}" hidden'
            alias_attr = f' data-aliases="{html.escape(aliases)}"' if aliases else ""
            parent_attr = ' data-nav-parent="true"' if children else ""
            item_indent = "                    " if children else "            "
            if children:
                if jinja:
                    branch_class = (
                        f" {{% if {active_expression} %}}is-expanded{{% endif %}}"
                    )
                    branch_expanded = (
                        f"{{% if {active_expression} %}}true{{% else %}}false{{% endif %}}"
                    )
                    branch_action = (
                        f"{{% if {active_expression} %}}收起{{% else %}}展开{{% endif %}}"
                    )
                else:
                    is_expanded = item_id == active_id
                    branch_class = " is-expanded" if is_expanded else ""
                    branch_expanded = "true" if is_expanded else "false"
                    branch_action = "收起" if is_expanded else "展开"
                lines.extend([
                    f'            <div class="nav-branch{branch_class}">',
                    '                <div class="nav-branch-row">',
                ])
            lines.extend([
                f'{item_indent}<a class="nav-item{active}" href="{item["href"]}"'
                f'{alias_attr}{optional}{current}{parent_attr}>',
                f'{item_indent}    <span class="nav-icon" aria-hidden="true">'
                f'<svg viewBox="0 0 24 24">{item["svg"]}</svg></span>',
                f'{item_indent}    <span class="nav-label">{html.escape(item["label"])}</span>',
                f'{item_indent}</a>',
            ])
            if children:
                lines.extend([
                    f'                    <button class="nav-branch-toggle" type="button" '
                    f'aria-expanded="{branch_expanded}" aria-controls="nav-{item_id}-children" '
                    f'aria-label="{branch_action}{html.escape(item["label"])}二级导航">',
                    '                        <svg viewBox="0 0 16 16" aria-hidden="true">'
                    '<path d="m4 6 4 4 4-4"/></svg>',
                    '                    </button>',
                    '                </div>',
                ])
                lines.append(
                    f'                <nav class="nav-subitems" id="nav-{item_id}-children" '
                    f'aria-label="{html.escape(item["label"])}二级导航">'
                )
                for child in children:
                    aliases = ",".join(child.get("aliases", []))
                    alias_attr = (
                        f' data-aliases="{html.escape(aliases)}"' if aliases else ""
                    )
                    section_attr = (
                        f' data-review-section="{html.escape(child["section"])}"'
                        if child.get("section") else ""
                    )
                    if jinja:
                        child_expression = _exact_active_expression(child)
                        child_active = (
                            f" {{% if {child_expression} %}}is-active{{% endif %}}"
                        )
                        child_current = (
                            f" {{% if {child_expression} %}}aria-current=\"page\"{{% endif %}}"
                        )
                    else:
                        default_child = item_id == active_id and child.get("section") == "daily"
                        child_active = " is-active" if default_child else ""
                        child_current = ' aria-current="page"' if default_child else ""
                    lines.extend([
                        f'                    <a class="nav-subitem{child_active}" href="{child["href"]}"'
                        f'{alias_attr} data-nav-match="exact"{section_attr}{child_current}>',
                        f'                        <span class="nav-label">{html.escape(child["label"])}</span>',
                        '                    </a>',
                    ])
                lines.extend([
                    '                </nav>',
                    '            </div>',
                ])
        lines.extend([
            '        </div>',
            '    </section>',
        ])
    lines.extend([
        '</nav>',
        '<!-- PRODUCT_NAV_END -->',
    ])
    return "\n".join(lines)


def _indent_block(block: str, indent: str) -> str:
    return "\n".join(f"{indent}{line}" if line else "" for line in block.splitlines())


def _replace_navigation(source: str, navigation_html: str) -> str:
    match = MARKED_NAV_RE.search(source) or NAV_RE.search(source)
    if not match:
        raise RuntimeError("navigation block not found")
    return source[:match.start()] + _indent_block(navigation_html, match.group("indent")) + source[match.end():]


def _replace_with_partial(source: str) -> str:
    match = NAV_RE.search(source)
    if not match:
        if '{% include "partials/product_navigation.html" %}' in source:
            return source
        raise RuntimeError("Jinja navigation block not found")
    include = f'{match.group("indent")}{{% include "partials/product_navigation.html" %}}'
    return source[:match.start()] + include + source[match.end():]


def _ensure_feature_script(source: str, version: str) -> str:
    desired = f'/static/js/ui-features.js?v={version}'
    if "ui-features.js" in source:
        return re.sub(r'/static/js/ui-features\.js(?:\?v=[^"\']+)?', desired, source)
    match = APP_SHELL_SCRIPT_RE.search(source)
    if not match:
        raise RuntimeError("app-shell.js script tag not found")
    tag = f'{match.group("indent")}<script src="{desired}" defer></script>\n'
    return source[:match.start()] + tag + source[match.start():]


def _replace_legacy_versions(source: str, version: str) -> str:
    """Replace known handwritten shell versions with the page's version source."""
    return re.sub(
        r"(?<=\?v=)(?:20260712|20260722-blue)",
        version,
        source,
    )


def _version_local_assets(source: str, version: str) -> str:
    """Give every local CSS/JS reference one deterministic page version."""
    pattern = re.compile(
        r'(?P<path>(?:/static/)?(?:css|js)/[^"\'?#]+)(?:\?v=[^"\']+)?'
    )
    return pattern.sub(lambda match: f'{match.group("path")}?v={version}', source)


def _planned_files() -> dict[Path, str]:
    navigation = _load_navigation()
    feature_hash = _feature_digest()
    static_asset_hash = _static_asset_digest()
    planned: dict[Path, str] = {}

    partial = _render_navigation(navigation, active_id=None, jinja=True) + "\n"
    planned[PARTIAL_PATH] = partial

    for path, active_id in STATIC_TARGETS.items():
        if not path.exists():
            continue
        source = path.read_text(encoding="utf-8")
        source = _replace_navigation(
            source,
            _render_navigation(navigation, active_id=active_id, jinja=False),
        )
        version = static_asset_hash if path in DIRECT_STATIC else "__ASSET_VERSION__"
        source = _version_local_assets(source, version)
        source = _ensure_feature_script(
            source,
            feature_hash if path in DIRECT_STATIC else version,
        )
        source = _replace_legacy_versions(source, version)
        planned[path] = source

    for path in JINJA_TARGETS:
        source = path.read_text(encoding="utf-8")
        source = _replace_with_partial(source)
        source = _ensure_feature_script(source, "{{ asset_ver }}")
        planned[path] = source

    # Root `/` is a marketing landing page without the product shell sidebar.
    # Only rewrite views.py when a navigation block is still present (legacy).
    views_source = VIEWS_PATH.read_text(encoding="utf-8")
    if MARKED_NAV_RE.search(views_source) or NAV_RE.search(views_source):
        views_source = _replace_navigation(
            views_source,
            _render_navigation(navigation, active_id="single_study", jinja=False),
        )
        views_source = _ensure_feature_script(views_source, feature_hash)
        planned[VIEWS_PATH] = views_source
    return planned


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    planned = _planned_files()
    changed = [
        path for path, content in planned.items()
        if not path.exists() or path.read_text(encoding="utf-8") != content
    ]
    if args.check:
        if changed:
            for path in changed:
                print(f"navigation drift: {path.relative_to(PROJECT_ROOT)}")
            return 1
        print("product navigation is synchronized")
        return 0

    for path in changed:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(planned[path], encoding="utf-8")
        print(f"updated {path.relative_to(PROJECT_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
