from video_transcript_api.transcriber.control_database import (
    CompatRow,
    _replace_qmark_placeholders,
    _escape_literal_percents,
    _split_sql_script,
    _translate_postgres_sql,
)


def test_compat_row_supports_mapping_and_integer_access() -> None:
    row = CompatRow(["id", "title"], [7, "Lesson"])

    assert row[0] == row["id"] == 7
    assert row[1] == row["title"] == "Lesson"
    assert dict(row) == {"id": 7, "title": "Lesson"}


def test_qmark_translation_preserves_quoted_question_marks() -> None:
    statement = "SELECT '?' AS literal, value FROM records WHERE id = ? AND note = 'it''s ?'"

    assert _replace_qmark_placeholders(statement) == (
        "SELECT '?' AS literal, value FROM records "
        "WHERE id = %s AND note = 'it''s ?'"
    )


def test_sqlite_dialect_translation_covers_repository_statements() -> None:
    ddl = "CREATE TABLE sample (id INTEGER PRIMARY KEY AUTOINCREMENT, enabled BOOLEAN)"
    insert = "INSERT OR IGNORE INTO sample (enabled) VALUES (?)"
    query = "SELECT IFNULL(enabled, 0) FROM sample WHERE id = ?"

    assert "GENERATED BY DEFAULT AS IDENTITY" in _translate_postgres_sql(ddl)
    assert "enabled INTEGER" in _translate_postgres_sql(ddl)
    assert _translate_postgres_sql(insert).endswith("ON CONFLICT DO NOTHING")
    assert _translate_postgres_sql(query) == (
        "SELECT COALESCE(enabled, 0) FROM sample WHERE id = %s"
    )


def test_script_splitter_ignores_semicolons_inside_strings() -> None:
    script = "INSERT INTO sample(value) VALUES ('a;b'); SELECT 1;"

    assert _split_sql_script(script) == [
        "INSERT INTO sample(value) VALUES ('a;b')",
        "SELECT 1",
    ]


def test_percent_escaping_only_changes_sql_literals() -> None:
    statement = "SELECT * FROM jobs WHERE id = %s AND error LIKE '%upload_failed%'"

    assert _escape_literal_percents(statement) == (
        "SELECT * FROM jobs WHERE id = %s AND error LIKE '%%upload_failed%%'"
    )
